Login setup
Iqbal-Elham/Doctor-Reservation-frontend pull request #7
Opened 2023-07-26 09:12 UTC by Iqbal-Elham

## In this pull I implemented the following requirements:

- The user logs in to the website, only by typing the username.
- Design and implement login page
![capture1](https://github.com/Iqbal-Elham/Doctor-Reservation-frontend/assets/49829914/f2fca40d-40d9-44e7-93e6-a32a92319a76)
![Capture2](https://github.com/Iqbal-Elham/Doctor-Reservation-frontend/assets/49829914/943715f0-bc08-4d68-8383-b36eb3c3ca9f)

2023-07-26 14:38 UTC, Muhammad0602 commented
@Iqbal-Elham why didn't you add the password and email.

2023-07-26 14:38 UTC, Muhammad0602 commented
What will happen if we have 2 users with the same username, will we ask them to change their name? 😁

2023-07-26 14:39 UTC, Muhammad0602 requested changes
Hi @Iqbal-Elham  , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- The app works as expected ✔️ 
- Good UI ✔️ 
- Linter checks pass


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-26 14:43 UTC, Muhammad0602 commented
Also I noticed that when the user is signing in or login he has access to entire navigation panel, which should not be the case. I think @mrkamin should fix that as it is his part.

2023-07-27 05:37 UTC, Iqbal-Elham commented
Hi @Muhammad0602, hope you are doing great, Thank you for reviewing my pull request and your nice feedback. In case of email and password I think it is not required for us because we are group of 4 and in case of username duplicating I fix the issue you can checkout it out again whenever you had time. ❤️ 🙏🏻

2023-07-27 13:09 UTC, mrkamin approved these changes
Hello @Iqbal-Elham  ,

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

2023-07-28 15:01 UTC, Muhammad0602 approved these changes
Hi @Iqbal-Elham, 
Great job, your project is now complete.

2023-07-28 15:01 UTC, Muhammad0602 commented on src/components/loginpage/Login.js
> +        </form>
You should consider adding a field for the email and password for the login and password confirmation for sign up.

2023-07-30 05:13 UTC, merged